version: '3.7'
services:

  # Database: mariaDB
  database:
    image: mariadb:latest
    container_name: mariadb
    volumes:
      # Configuration
      - "./docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf"
      # Keep DB data 
      - "./docker/mariadb/data:/var/lib/mysql"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    restart: always
